name: Test workflow
on:
  workflow_dispatch:

jobs:
  calculate-and-send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ vars.REPOSITORY }}
          ref: ${{ vars.REF }}

      - name: Setup uv
        uses: astral-sh/setup-uv@v3
        with:
          version: '0.5.4'

      - name: Run script
        env:
          ZOTERO_ID: ${{ secrets.ZOTERO_ID }}
          ZOTERO_KEY: ${{ secrets.ZOTERO_KEY }}
          ZOTERO_IGNORE: ${{ vars.ZOTERO_IGNORE }}
          SEND_EMPTY: ${{ vars.SEND_EMPTY }}
          ARXIV_QUERY: "cs.AI+cs.CV+cs.DS+cs.GT+cs.LG+cs.LO+cs.NE+cs.SC+stat.TH+stat.ML+stat.AP"
          SMTP_SERVER: "stmp.qq.com"
          SMTP_PORT: 465
          SENDER: "johnnyxqliao@qq.com"
          RECEIVER: "johnnyxqliao@gmail.com"
          SENDER_PASSWORD: "wulnlwgdapqrhfbg"
          MAX_PAPER_NUM: -1
          USE_LLM_API: ${{ secrets.USE_LLM_API }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_BASE: ${{ secrets.OPENAI_API_BASE }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          LANGUAGE: ${{ vars.LANGUAGE }}
        run: |
          uv run main.py
